name = "JuliQAOALab"
uuid = "12345678-1234-1234-1234-123456789abc"
authors = [ "Ben",]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
